name: CI
on:
  push:
    branches: [ main ]
    tags: ['*']

  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Course Management Tools Repo
        uses: actions/checkout@v2
        with:
          path: CMT
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Ivy
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy--${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-ivy-
            ${{ runner.os }}-

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('project/**') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-

      - name: Run tests
        run: sbt test